In [32]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, median_absolute_error, r2_score, accuracy_score, balanced_accuracy_score
from sklearn.feature_selection import mutual_info_regression
from sdv.tabular import TVAE
import matplotlib.pyplot as plt

In [19]:
train = pd.read_csv("./data/multi/train_hydraulic.csv", sep=",")

drop_cols = ["Turbine_ID", "Timestamp", "Unnamed: 0", "index_y"]
train = train.drop(columns = drop_cols)

fill_method="ffill"
train = train.fillna(method=fill_method)

remove_n = 230000
drop_indices = np.random.choice(train.index, remove_n, replace=False)
train = train.drop(drop_indices)
train.head

<bound method NDFrame.head of         Gen_RPM_Max  Gen_RPM_Min  Gen_RPM_Avg  Gen_RPM_Std  Gen_Bear_Temp_Avg  \
20            272.7        116.8        208.8         46.0               36.0
30           1114.6        120.0        400.4        363.4               33.0
32            174.3        104.0        133.8         16.7               32.0
73           1592.4       1250.5       1402.6         98.1               42.0
79           1606.4       1243.8       1433.8         87.2               47.0
...             ...          ...          ...          ...                ...
259677       1592.3       1233.7       1374.8        108.5               43.0
259683       1568.2       1252.5       1385.7         83.5               44.0
259685       1444.8       1228.1       1279.3         42.9               43.0
259693       1286.7       1231.9       1252.7          9.4               40.0
259701       1389.6        208.9        533.9        417.0               36.0

        Gen_Phase1_Temp_Avg  Gen_Phase2_Temp_Avg  Gen_Phase3_Temp_Avg  \
20                       38                   39                   38
30                       39                   39                   40
32                       39                   39                   39
73                       52                   53                   53
79                       57                   58                   58
...                     ...                  ...                  ...
259677                   64                   64                   64
259683                   65                   65                   65
259685                   65                   65                   64
259693                   61                   61                   61
259701                   51                   51                   51

        Hyd_Oil_Temp_Avg  Gear_Oil_Temp_Avg  ...  Max_Humidity  Avg_Humidity  \
20                    31                 42  ...          91.0          89.0
30                    31                 41  ...          95.0          95.0
32                    31                 41  ...          95.0          95.0
73                    31                 46  ...          83.0          82.0
79                    31                 48  ...          86.0          85.0
...                  ...                ...  ...           ...           ...
259677                33                 48  ...          61.0          60.0
259683                33                 49  ...          61.0          60.0
259685                33                 49  ...          61.0          60.0
259693                32                 47  ...          61.0          60.0
259701                33                 43  ...          61.0          60.0

        Min_Precipitation  Max_Precipitation  Avg_Precipitation  \
20                    0.0                0.0                0.0
30                    0.0                0.0                0.0
32                    0.0                0.0                0.0
73                    0.0                0.0                0.0
79                    0.0                0.0                0.0
...                   ...                ...                ...
259677                0.0                0.0                0.0
259683                0.0                0.0                0.0
259685                0.0                0.0                0.0
259693                0.0                0.0                0.0
259701                0.0                0.0                0.0

        Max_Raindetection  Anemometer1_Avg_Freq  Anemometer2_Avg_Freq  \
20                    0.0                  71.0                  72.0
30                    0.0                  43.0                  39.0
32                    0.0                  19.0                  19.0
73                    0.0                 148.0                 150.0
79                    0.0                 148.0                 149.0
...                   ...                   ...                   ...
259677                0.0                  83.0                  82.0
259683                0.0                  83.0                  82.0
259685                0.0                  83.0                  82.0
259693                0.0                  83.0                  82.0
259701                0.0                  83.0                  82.0

        Pressure_Avg_Freq  Risk Level
20                  417.0    med-high
30                  416.0    med-high
32                  416.0    med-high
73                  417.0    med-high
79                  417.0    med-high
...                   ...         ...
259677              417.0      medium
259683              417.0      medium
259685              417.0      medium
259693              417.0      medium
259701              417.0      medium

[29710 rows x 104 columns]>

In [20]:
ctgan = TVAE(
    #verbose=True,
    #batch_size=1000,
    #generator_dim=(64, 64, 64),
    #discriminator_dim=(64, 64, 64)
)
categorized_cols = ["Risk Level"]
ctgan.fit(train)#, categorized_cols, epochs=20)

In [21]:
sammples = ctgan.sample(29710)

In [22]:
sammples.describe()

,Gen_RPM_Max,Gen_RPM_Min,Gen_RPM_Avg,Gen_RPM_Std,Gen_Bear_Temp_Avg,Gen_Phase1_Temp_Avg,Gen_Phase2_Temp_Avg,Gen_Phase3_Temp_Avg,Hyd_Oil_Temp_Avg,Gear_Oil_Temp_Avg,...,Min_Humidity,Max_Humidity,Avg_Humidity,Min_Precipitation,Max_Precipitation,Avg_Precipitation,Max_Raindetection,Anemometer1_Avg_Freq,Anemometer2_Avg_Freq,Pressure_Avg_Freq
count,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,...,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.0,29710.000000,29710.000000,29710.000000
mean,1261.136489,810.448118,1046.532851,109.798485,42.485560,63.068899,62.123460,61.145742,34.363817,46.837058,...,63.428509,66.329822,64.670010,0.000067,0.002592,0.001515,0.0,120.751094,117.834837,413.123763
std,572.371503,634.664106,594.671504,156.666107,13.900568,24.945407,25.773412,24.029548,8.322787,6.628626,...,13.408372,14.675262,13.956242,0.008205,0.050844,0.038890,0.0,64.417027,65.307536,5.768125
min,0.000000,0.000000,0.000000,0.000000,18.000000,20.000000,19.000000,20.000000,21.000000,25.000000,...,13.000000,19.000000,14.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,392.000000
25%,1265.500000,70.950000,294.000000,18.000000,33.000000,45.000000,42.000000,44.000000,28.000000,42.000000,...,57.000000,58.000000,58.000000,0.000000,0.000000,0.000000,0.0,83.000000,81.000000,409.000000
50%,1415.650000,1223.100000,1274.000000,44.000000,40.000000,60.000000,59.000000,58.000000,31.000000,47.000000,...,61.000000,63.000000,61.000000,0.000000,0.000000,0.000000,0.0,102.000000,98.000000,413.000000
75%,1675.200000,1271.100000,1537.000000,99.000000,48.000000,77.000000,76.000000,72.000000,39.000000,53.000000,...,71.000000,77.000000,74.000000,0.000000,0.000000,0.000000,0.0,146.000000,147.000000,418.000000
max,1914.700000,1663.700000,1684.000000,790.000000,98.000000,149.000000,193.000000,150.000000,55.000000,61.000000,...,100.000000,100.000000,100.000000,1.000000,1.000000,1.000000,0.0,425.000000,427.000000,428.000000

In [23]:
train.describe()

,Gen_RPM_Max,Gen_RPM_Min,Gen_RPM_Avg,Gen_RPM_Std,Gen_Bear_Temp_Avg,Gen_Phase1_Temp_Avg,Gen_Phase2_Temp_Avg,Gen_Phase3_Temp_Avg,Hyd_Oil_Temp_Avg,Gear_Oil_Temp_Avg,...,Min_Humidity,Max_Humidity,Avg_Humidity,Min_Precipitation,Max_Precipitation,Avg_Precipitation,Max_Raindetection,Anemometer1_Avg_Freq,Anemometer2_Avg_Freq,Pressure_Avg_Freq
count,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,...,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.000000,29710.0,29710.000000,29710.000000,29710.000000
mean,1164.108647,912.179408,1041.054638,67.620727,44.473241,61.919084,62.080646,61.295927,34.328711,47.374184,...,66.523763,68.888253,67.675732,0.036452,0.104510,0.069135,0.0,114.685123,114.364389,411.477314
std,641.051311,611.271792,615.860201,110.905613,15.268239,27.032403,26.539198,25.702959,7.695197,6.917558,...,15.438340,15.051179,15.222622,0.527717,1.186396,0.925914,0.0,67.945399,68.306137,5.652230
min,0.000000,0.000000,0.000000,0.000000,18.000000,20.000000,19.000000,20.000000,21.000000,25.000000,...,13.000000,14.000000,13.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,392.000000
25%,297.000000,183.400000,255.000000,13.600000,33.000000,40.000000,41.000000,40.000000,28.000000,42.000000,...,59.000000,61.000000,60.000000,0.000000,0.000000,0.000000,0.0,75.000000,75.000000,407.000000
50%,1398.900000,1231.500000,1270.550000,28.200000,42.000000,58.000000,59.000000,58.000000,32.000000,48.000000,...,64.000000,67.000000,66.000000,0.000000,0.000000,0.000000,0.0,87.000000,87.000000,411.000000
75%,1676.300000,1344.100000,1569.575000,69.200000,53.000000,73.000000,74.000000,73.000000,39.000000,53.000000,...,78.000000,80.000000,79.000000,0.000000,0.000000,0.000000,0.0,149.000000,149.000000,417.000000
max,1923.200000,1663.700000,1683.500000,789.600000,205.000000,205.000000,205.000000,205.000000,55.000000,61.000000,...,100.000000,100.000000,100.000000,31.000000,79.000000,74.000000,0.0,425.000000,427.000000,428.000000

In [24]:
#Export
ctgan.save("./data/multi/model")
train.to_csv("./data/multi/train_hydraulic_generator_base.csv")
sammples.to_csv("./data/multi/train_hydraulic_generated.csv")

In [25]:
#Reimport
ctgan = ctgan.load("./data/multi/model")

class_target_name = "Risk Level"

train = pd.read_csv("./data/multi/train_hydraulic.csv", sep=",")

drop_cols = ["Turbine_ID", "Timestamp", "Unnamed: 0", "index_y"]
train = train.drop(columns = drop_cols)

fill_method="ffill"
train = train.fillna(method=fill_method)

base = train
generated_same = sammples
generated_half = ctgan.sample(15000)
generated_double = ctgan.sample(60000)
generated_fact10 = ctgan.sample(120000)

test = pd.read_csv("./data/multi/test_hydraulic.csv", sep=",")
drop_cols = ["Turbine_ID", "Timestamp", "Unnamed: 0", "index_y"]
test = test.drop(columns = drop_cols)
fill_method="ffill"
test = test.fillna(method = fill_method)
test = test.fillna(method = "backfill")

In [26]:
test.notna()

,Gen_RPM_Max,Gen_RPM_Min,Gen_RPM_Avg,Gen_RPM_Std,Gen_Bear_Temp_Avg,Gen_Phase1_Temp_Avg,Gen_Phase2_Temp_Avg,Gen_Phase3_Temp_Avg,Hyd_Oil_Temp_Avg,Gear_Oil_Temp_Avg,...,Max_Humidity,Avg_Humidity,Min_Precipitation,Max_Precipitation,Avg_Precipitation,Max_Raindetection,Anemometer1_Avg_Freq,Anemometer2_Avg_Freq,Pressure_Avg_Freq,Risk Level
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157426,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
157427,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
157428,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
157429,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
157430,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [33]:
def split_x_y(data:DataFrame ,target_name: str):
    drop = [target_name]
    x = data.drop(columns=target_name)
    y = data[target_name]
    return x,y

def checkNaN(data: DataFrame):
    re = str(data.isnull().sum().sum())
    #print(re)
    return re

def get_eval_scores(inputs_train:DataFrame, targets_train:DataFrame, inputs_test:DataFrame, targets_test:DataFrame):    
    dtr = DecisionTreeClassifier(random_state=0)
    dtr.fit(inputs_train, targets_train)
    eval_predict = dtr.predict(inputs_test)
    accuracy = balanced_accuracy_score(targets_test, eval_predict)
    return accuracy

def train_run(data: DataFrame, test:DataFrame):
    train_x, train_y = split_x_y(data, class_target_name)    
    test_x, test_y = split_x_y(test, class_target_name)
    return get_eval_scores(train_x, train_y, test_x, test_y)

In [34]:
base_accuracy = train_run(base, test)
generated_fact10_accuracy = train_run(generated_fact10, test)
combined = pd.concat([generated_fact10, base])
combined_accuracy = train_run(combined,test)
print("eBas:" + str(base_accuracy))
print("Generated_Only:" + str(generated_fact10_accuracy))
print("Combined:" + str(combined_accuracy))

eBas:0.17427780578983385
Generated_Only:0.20025512003883175
Combined:0.1864643029063269

In [35]:
print(generated_same)

       Gen_RPM_Max  Gen_RPM_Min  Gen_RPM_Avg  Gen_RPM_Std  Gen_Bear_Temp_Avg  \
0            203.1          0.0        213.0         15.0               30.0
1           1684.9       1585.9       1660.0         19.0               43.0
2           1283.6       1212.3       1254.0         12.0               43.0
3            197.5        171.6        151.0         24.0               26.0
4           1627.3       1232.2       1534.0        129.0               42.0
...            ...          ...          ...          ...                ...
29705       1754.4         28.1       1665.0         48.0               41.0
29706       1829.1       1622.6       1684.0         25.0               67.0
29707       1297.1       1239.0       1242.0          4.0               40.0
29708       1333.0        262.9        870.0        342.0               28.0
29709       1745.1        160.2       1164.0        457.0               72.0

       Gen_Phase1_Temp_Avg  Gen_Phase2_Temp_Avg  Gen_Phase3_Temp_Avg  \
0                       30                   36                   33
1                       65                   60                   63
2                       68                   63                   57
3                       31                   30                   30
4                       90                   77                   74
...                    ...                  ...                  ...
29705                   97                   84                   65
29706                   32                   79                   98
29707                   43                   40                   43
29708                   58                   41                   40
29709                   86                  107                  101

       Hyd_Oil_Temp_Avg  Gear_Oil_Temp_Avg  ...  Max_Humidity  Avg_Humidity  \
0                    31                 35  ...          61.0          55.0
1                    28                 52  ...          74.0          69.0
2                    39                 47  ...          64.0          68.0
3                    26                 31  ...          94.0          96.0
4                    30                 54  ...          61.0          60.0
...                 ...                ...  ...           ...           ...
29705                38                 48  ...          60.0          58.0
29706                40                 48  ...          82.0          71.0
29707                30                 38  ...          61.0          60.0
29708                27                 42  ...          75.0          72.0
29709                48                 55  ...          47.0          54.0

       Min_Precipitation  Max_Precipitation  Avg_Precipitation  \
0                    0.0                0.0                0.0
1                    0.0                0.0                0.0
2                    0.0                0.0                0.0
3                    0.0                0.0                0.0
4                    0.0                0.0                0.0
...                  ...                ...                ...
29705                0.0                0.0                0.0
29706                0.0                0.0                0.0
29707                0.0                0.0                0.0
29708                0.0                0.0                0.0
29709                0.0                0.0                0.0

       Max_Raindetection  Anemometer1_Avg_Freq  Anemometer2_Avg_Freq  \
0                    0.0                  73.0                  49.0
1                    0.0                 154.0                 134.0
2                    0.0                  86.0                 106.0
3                    0.0                  68.0                  80.0
4                    0.0                 161.0                 196.0
...                  ...                   ...                   ...
29705                0.0                 359.0                 409.0
29706                0.0                 328.0                 392.0
29707                0.0                  85.0                  82.0
29708                0.0                  61.0                  73.0
29709                0.0                  69.0                  58.0

       Pressure_Avg_Freq  Risk Level
0                  414.0         low
1                  416.0         low
2                  411.0         low
3                  405.0         low
4                  417.0         low
...                  ...         ...
29705              414.0         low
29706              419.0         low
29707              420.0         low
29708              421.0         low
29709              414.0         low

[29710 rows x 104 columns]